(* module Vec2 : sig *)
(*   type t = float * float *)
(* end *)
(* = *)
(* struct *)
(* end *)

(* module Vec3 : sig *)
(*   type t = float * float * float *)
(* end *)
(* = *)
(* struct *)
(* end *)

(* module Camera : sig *)
(*   type t *)
(* end *)
(* = *)
(* struct *)
(*   type t = { *)
(*     mutable pos : Vec3.t ; *)
(*     mutable orientation : Quaternion.t ; *)
(*   } *)
(* end *)

(* val make :  *)
